<h2>Üdvözöljük oldalunkon!</h2>
<img src="./images/kutyus.jpg">
<h3>AMENNYIBEN SEGÍTSÉGRE VAN SZÜKSÉGE A KIVÁLASZTÁSBAN</h3>
            <p>Vagy akár több szimpatikus állatot is talált, kérjük a budaorsiallatmenhely@gmail.com-ra küldött e-mailben vagy Facebookon privát üzenetben vegye fel velünk a kapcsolatot, mi segíteni fogunk. Ha a menhelyen akad meg a szeme egy kutyán vagy cicán, önkénteseink segítenek a továbbiakban. Abban az esetben, ha már van kutyájuk, javasoljuk, hogy őt is hozzák ki menhelyünkre (érvényes oltásokkal), derüljön ki, hogy szimpatikusak-e egymásnak, szoktathatók, vagy nem alkalmasak az együttélésre.</br>Amennyiben kisgyerek van a családban, kérjék ki tapasztalt önkénteseink véleményét a kiválasztott állat gyermekekhez való viszonyáról, és persze tanácsos kutyát és gyermeket ellenőrzött körülmények között megismertetni egymással.</br>Örökbefogadás előtt legalább 2-3 alkalommal jöjjenek el hozzánk, ezalatt megalapozott döntéssé válhat a kezdeti szimpátia.</br>A kifutókban élő felnőtt cicáinkhoz is bátran be lehet ülni, ismerkedni, beszélgetni velük, akár több alkalommal is, mielőtt a fontos elhatározás megszületik. Macskát kizárólag benti tartás céljából adunk örökbe.</br>Állataink két esetben lehetnek karanténban: vagy még “frissen” kerültek be menhelyünkre, ezért az oltási programjuk még folyamatban van, vagy betegség miatt. Első esetben az említett állat örökbefogadható, ha a leendő gazda felelősséget vállal az oltási program befejezésére, továbbá ha eleget tesz az oltás nélküli állatokkal kapcsolatban felmerülő óvintézkedéseknek. Beteg, fertőzött állatot csak tapasztalt, felelősségteljes gazdához adunk, megfelelő tájékoztatás után.</p>
			
           
			<h3>HA AZ ISMERKEDÉS JÓL SIKERÜLT</h3>
            <p>Jöhet az örökbefogadási szerződés aláírása, majd az állat új otthonába történő szállítása. Az örökbefogadási adomány egy általunk meghatározott minimális összeg, mely csekély részben fedezi az állattal kapcsolatban felmerült költségeket.</br>
			Az adomány mértéke az adott állat oltásainak, tesztjeinek számától, illetve attól függ, hogy ivartalanított-e. Jelenleg az adomány általunk kalkulált összege: cica esetén 15.000,- Ft (chipezett, ivartalanított, FELV/FIV tesztelt), kutya esetén 25.000,- Ft (kétszer oltott, chipezett, ivartalanított, szív- és bőrféregre tesztelt). Szív- és bőrféreg tesztelés nélküli összeg kutya esetén 20.000,- Ft. (Egyedi esetben a menhely fenntartja az adomány összegére vonatkozóan a változtatás jogát!) Természetesen magasabb összegű adományt szívesen fogadunk.</br>Ezeket az összegeket esetleg magasnak érzik, azonban vegyék figyelembe, hogy az állatainkra fordított orvosi kezelések, oltások, tesztek, az elfogyasztott táplálék stb. összesített költsége jóval több, mint az örökbefogadási díj. Ha ezeket az oltásokat, ivartalanítást, stb., Ön végezteti el, a fenti összegek többszörösét fogja kifizetni. Indokolt esetben vállaljuk a kiválasztott állat gazdihoz történő kiszállítását.
			</p>
            <img src="images/cica.jpg">
			<h3>KUTYÁINKAT ÉS CICÁINKAT</h3>
            <p>ivartalanítva, oltva, chipelve, parazitamentesítve adjuk ki. Kölyökkutya/kölyökmacska az oltási program befejezésére vonatkozó, valamint ivartalanítási kötelezettséggel fogadható örökbe. Az ivartalanítás megtörténtét az ivarérett kor betöltését követően ellenőrizzük. Az ivartalanítás megtörténtéről szóló állatorvosi igazolás, illetve az oltási program befejezését igazoló oltási könyv bemutatásával nyilvánítjuk a kötelezettséget teljesítettnek.</br>Cicákat kizárólag megfelelően zárható macskaszállító kosárral érkező örökbefogadóknak tudunk kiadni. A cicát örökbefogadóknak a macskaboxra sok éven keresztül, a macska élete végéig szüksége lesz, tehát egy elengedhetetlen és hosszú távra szóló beruházás, így ezt még az örökbefogadás előtt be kell szerezni. Az örökbefogadott állat új környezetbe kerülése nagy stressz egy élőlény számára. Kérjük, hogy türelemmel, szeretettel terelgessék az új jövevényt, hogy mielőbb megtalálja helyét a családban. Időre van szükség, mire az új "falka" összecsiszolódik.</br>Kérdéssel, problémával kapcsolatban tapasztalt kollégáink szívesen segítenek, Facebook-on vagy e-mailben vagy telefonon várjuk kérdéseiket. Fontos számunkra, hogy a tőlünk elköltözött állatainkat nyomon tudjuk követni, ezért a kezdeti időkben gyakori visszajelzést kérünk az új gazdiktól, a későbbiekben pedig ritkább bejelentkezéseknek is nagyon örülünk. Számunkra nincs nagyobb öröm, mint visszajelzést kapni arról, hogy egy régi védencünk szerető otthonban él.</br>Menhelyünk fenntartja az állat környezetére vonatkozó ellenőrzési jogot, a gazdával előre egyeztetett időpontban. A tőlünk örökbe fogadott állatot továbbadni más magánszemélynek vagy más menhelyre beadni nem lehet. Az örökbefogadott állatot bármikor visszavesszük, a gazda az örökbefogadási szerződésben kötelezettséget vállal arra nézve, hogy amennyiben az állatról bármilyen okból le kíván mondani, akkor csak és kizárólag menhelyünkön adhatja le.</br>És végezetül tisztelettel megkérünk minden örökbefogadót, hogy az általunk kialakított szabályokat, elveket, metódusokat legyen szíves tiszteletben tartani. Azok kialakítására mentett állataink érdekében került sor.
			</br>Köszönjük, hogy szánt néhány percet a fentiekre, és hogy átgondolja jelenleg tud-e Ön egy életen át felelős és szerető gazdája lenni valamelyik védencünknek.
			</p>